### ISSUE TITLE
Finding a header mid-stream

### ISSUE THREAD

**Issue by madelynnblue** [korandiz/mpa#1]
I'm trying to use mpa to play data from icecast. That protocol starts streaming mp3 data from an unknown location. Thus, correctly finding the next frame header is important for the mp3 decoder. I have captured a small sample of a stream, which plays correctly in mplayer. When run by mpa, though, it finds something that might be a header, attempts to decode the following frame, fails, and then exits.

I have modified my copy of mpa so that if frame decoding fails, it returns to searching for another valid frame. However, since many bytes have been read during the attempted frame decoding, the first valid frame's header has already been passed. I do not see an obvious way to modify the bitreader to stuff bytes back into the buffer, or for the findHeader function to be much smarter and verify that it has a valid frame before proceeding (for example determining where the next correct frame header would be and seeing if it's there and correct).

I can provide an example mp3 of this behavior if you like.

**Comment by korandiz** [comment]
When I was writing the decoder I was aware of that false syncwords can appear in an MPEG stream, I just didn't think they would be a very big problem. Apparently, I was wrong.

The issue should have been fixed by this commit: 7a1160700aa2d37465110e7957424204b4b139b8

Please note that the first few calls to DecodeFrame may still fail with a MalformedStream, as mp3 frames aren't self-contained, and the required main_data may be several frames back in the stream. These errors are now safe to ignore.

**Comment by madelynnblue** [comment]
Fantastic. This is working now. Thanks.
